import Head from "next/head";
import styles from "../styles/Home.module.css";
import Image from "next/image";
import HomePage from "./homePage";
import Services from "./services";

import Footer from "../components/Footer";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Estevão Mbala | Desenvolvedor Fullstack</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
			</Head>
			<HomePage />
			<Services />
			<Footer />
		</div>
	);
}
